# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defaults:
  - /variables/volume: stokes
  - _self_

etl:
  # Common settings
  common:
    kind: stokes
    model_type: volume  # STL geometry + volume data

  processing:
    num_processes: 12
    args: {}

  source:
    _target_: data_sources.StokesFlowDataSource
    _convert_: all

    input_dir: ???  # Path to input dataset directory (required)
    kind: ${etl.common.kind}
    model_type: ${etl.common.model_type}

  transformations:
    # STL geometry transformation
    stl_preprocessing:
      _target_: data_transformations.StokesFlowSTLTransformation
      _convert_: all
      geometry_processors:
        - _target_: stokes_geometry_processors.update_geometry_to_float32
          _partial_: true

    # Volume data transformation (point-centered)
    volume_preprocessing:
      _target_: data_transformations.StokesFlowVolumeTransformation
      _convert_: all
      volume_processors:
        - _target_: stokes_volume_processors.update_volume_to_float32
          _partial_: true
        - _target_: stokes_volume_processors.shuffle_volume_data
          _partial_: true
          seed: 42

    # Zarr format transformation
    write_ready_transformation:
      _target_: data_transformations.StokesFlowZarrTransformation
      _convert_: all
      compression_method: zstd
      compression_level: 5
      chunk_size_mb: 1.0
      chunks_per_shard: 1000

  sink:
    _target_: data_sources.StokesFlowDataSource
    _convert_: all

    output_dir: ???  # Path to output directory (required)
    kind: ${etl.common.kind}
    serialization_method: zarr
    overwrite_existing: true