# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

defaults:
  - /external_aero_etl_drivaerml
  - override /variables/surface: hlpw
  - override /variables/volume: hlpw
  - override /variables/global: hlpw
  - _self_

etl:
  common:
    kind: hlpw
    model_type: combined  # produce data for which model? surface, volume, combined

  processing:
    num_processes: 32

  transformations:
    surface_preprocessing:
      # Use HLPW-specific transformation that handles N_BF field
      _target_: data_transformations.ExternalAerodynamicsSurfaceTransformationHLPW
      _convert_: all
      nbf_field_name: "N_BF"

      surface_processors:
        # Do not perform mesh decimation
        # normalize_surface_normals not needed - already done via N_BF normalization
        # HLPW-specific non-dimensionalization
        - _target_: external_aero_surface_data_processors.non_dimensionalize_surface_fields_hlpw
          _partial_: true
          pref: 176.352
          tref: 518.67
          qref: 4.94
        - _target_: external_aero_surface_data_processors.update_surface_data_to_float32
          _partial_: true

    volume_preprocessing:
      _target_: data_transformations.ExternalAerodynamicsVolumeTransformation
      _convert_: all
      volume_processors:
        - _target_: external_aero_volume_data_processors.non_dimensionalize_volume_fields_hlpw
          _partial_: true
          pref: 176.352
          tref: 518.67
          uref: 2679.505
          qref: 4.94
        - _target_: external_aero_volume_data_processors.update_volume_data_to_float32
          _partial_: true
        - _target_: external_aero_volume_data_processors.shuffle_volume_data
          _partial_: true

    global_params_preprocessing:
      _target_: data_transformations.ExternalAerodynamicsGlobalParamsTransformation
      _convert_: all
      global_parameters: ${etl.global_parameters}
      global_params_processors:
        - _target_: external_aero_global_params_data_processors.process_global_params_hlpw
          _partial_: true
